server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vinmusic?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      jedis:
        pool:
          min-idle: 100
          max-idle: 300
          max-wait: -1
          max-active: 100
      timeout: 3000
mybatis:
  type-aliases-package: sld.vinmusic
  mapper-locations: classpath:mapper/*Mapper.xml